activityspark/config/routes.rb
CountMeIn::Application.routes.draw do
  resources :posts

  get "testme/test"

  resources :pledges

  resources :events

  root :to => "events#index"

  resource :create do
    member do
      get 'add_payment'
    end
  end
  
  get "invitefriends/composemail"
  get "invitefriends/sendinvite"
  match "invitefriends/sendinvite" => "invitefriends#sendinvite", :via => :post

  get "emailcommentform/sendemail"

  match ':controller(/:action(/:id(.:format)))'
end

activityspark/app/models/event.rb
class Event < ActiveRecord::Base
end

activityspark/app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
	
	render :layout => false
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, :notice => 'Event was successfully created.' }
        format.json { render :json => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, :notice => 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end
end

activityspark/app/helpers/events_helper.rb
module EventsHelper
end

activityspark/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

activityspark/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

activityspark/app/views/events/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Activity Spark</title>
  <map name="FPMap0" id="FPMap0">
<area href="/events" shape="polygon" coords="405, 72, 472, 71, 472, 97, 409, 97" />
<area href="/aboutus" shape="polygon" coords="487, 73, 551, 72, 551, 98, 488, 98" />
</map>
  <%= stylesheet_link_tag    "events" %>
  <%= javascript_include_tag "events" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="mainContent">
	<div id="frontpage-container">
		<div id="frontpage-header" style="text-align:center">
			<div id="slides">
				<div class="slides_container">
					<div><%= link_to :controller => :events, :action =>:show, :id => 1 do %><%= image_tag "LouieFoxx_small.png", :alt => "slide1"%><% end %></div>
				</div>
			</div>
		</div>
	</div>

	<div id="frontpage-content">
	</div>


<div id="legal">About Us | Privacy Policy | Terms &amp; Conditions | &copy; Our Company, Inc 2012 - All rights reserved</div>

</div>
</body>
</html>

activityspark/app/views/events/invite_friends.html.erb
<script>
    $("#friendCustomMessage").live("keyup",function () {
        $("#customMsgTxt").html($("#friendCustomMessage").val());
    });

    function showCustomMessageField() {
        $("#showCustomMessageOption").hide();
        $("#customMessageTextBox").show();
    }

    var friendEmailAddressBoxRows = 2
    $(document).ready(function () {
        $("#friendEmailAddreses").live("keyup", function (e) {
            var keycode;
            if (window.event) keycode = window.event.keyCode;
            else if (e) keycode = e.which;
            else return true;
            if (keycode == 13) {
                friendEmailAddressBoxRows += 1;
                $("#friendEmailAddreses").attr("rows", friendEmailAddressBoxRows);
            }
        });

    });
</script>

        <div style="text-align:center;">
	<%= form_for @pledge, :method => :put, :url => { :action => :check_out } do |f| %>
            <div id="inviteFriendFormContents">
                <div id="inviteYourFriendsHeader">
                    <h2>Invite Your Friends</h2>
                </div>
                <div>
                    <div id="emailAddressHeader">Email Addresses: (one email per line)</div>
                    <div><textarea id="friendEmailAddreses" cols="50" rows="2"></textarea></div>
                </div>
                <div>
                <br />
                    Preview Message:
                    <div id="emailPreviewBox">
                        <p>Frank (email@address.com) has invited you to join him at this event.</p>
                        <p>
                            <b>Event Details:</b> <br /><br />
                            Title: Title <br />
                            Location: Location <br />
                            Date/Time: Date/Time <br />
                        </p>
                        <p>
                            <b>Frank's Message:</b>
                            <div id="customMsgTxt"></div>
                        </p>
                        <p>
                            <%= link_to "Click here", "#" %> to see more details and to join Frank at this event!
                        </p>
                        <p>
                            Enjoy! <br />
                            Count Me In!
                        </p>
                    </div>
                </div>
                <div onclick="showCustomMessageField()" id="showCustomMessageOption">Add Custom Message</div>
                <div id="customMessageTextBox">
                    <br />
                    <div id="customMessageHeading">Custom Message:</div>
                    <div><textarea id="friendCustomMessage" cols="50" rows="6"></textarea></div>
                </div>
                <div style="text-align:right;margin-top:20px;">
                    <div><input type="submit" value="Continue to Checkout" id="sendFriendInvites" /></div>
                </div>
            </div>
	<% end %>
        </div>

activityspark/app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

activityspark/app/views/events/show.html.erb
    <script src="jquery-1.7.1.min.js" type="text/javascript"></script>    
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBUsJXtpkGD72YiUBgOrk9jrz2eIr8QH-o&sensor=false">
    </script>

    <%= javascript_include_tag "gmap3"%>
    <%= stylesheet_link_tag "site"%>

    
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>

    <script type="text/javascript">
        function showAddress(address) 
        {
            $('#map_canvas').gmap3({
                action: 'addMarker',
                address: address,
                map: {
                    center: true,
                    zoom: 14
                },
                marker: {
                    options: {
                        draggable: false
                    }
                },
                infowindow: {
                    options: {
                    },
                    events: {
                        closeclick: function () {
                            alert("closing : " + $(this).attr("id"));
                        }
                    }
                }
            });
        }

        $(document).ready(function() {
            showAddress("<%= @event.location %>");
        });


    </script>

    <div id="pageBodyContainer">
        <div style="text-align:center;margin-top:25px;margin-bottom:25px;">
        <h2>Event Details</h2>
        </div>
        <div>
            <div style="float:left;display:none;"><img src="thumbnail.jpg" width="75px" /></div>
            <div id="eventDetailsContainer">
                <div><div class="eventDetailLabel">Title:</div> <div class="eventDetailValue"><%= @event.title %></div></div>
                <div><div class="eventDetailLabel">Location:</div> <div class="eventDetailValue"><%= @event.location %></div>
                <div><div class="eventDetailLabel">Date/Time:</div> <div class="eventDetailValue">Date/Time</div>
                <div><div class="eventDetailLabel">Price:</div> <div class="eventDetailValue">Price</div></div>
                <div<div class="eventDetailLabel">Description:</div> <div class="eventDetailValue">Desc</div></div>
                <br/><br/>
                <div id="makeAPledge"><%= link_to "Spark this Activity!", new_pledge_path(:event_id => @event) %></div>
            </div>

            <div id="eventDetailBox">
                <div id="map_canvas" style="width:100%; height:100%"></div>
                
            </div>
        </div>
    </div>