activityspark/config/routes.rb
CountMeIn::Application.routes.draw do
  resources :posts

  get "testme/test"

  resources :pledges

  resources :events

  root :to => "events#index"

  resource :create do
    member do
      get 'add_payment'
    end
  end
  
  get "invitefriends/composemail"
  get "invitefriends/sendinvite"
  match "invitefriends/sendinvite" => "invitefriends#sendinvite", :via => :post

  get "emailcommentform/sendemail"

  match ':controller(/:action(/:id(.:format)))'
end

activityspark/app/models/pledge.rb
class Pledge < ActiveRecord::Base
  has_many :participants
  has_many :notes
  
  validates :title, :num_people_required, :time, :location, presence: true
  validates :price_per_person, :num_people_required, :max_num_people, :curr_num_pledged, numericality: {greater_than_or_equal_to: 0.00}
  
  def get_host
    return self.participants[0]
  end
  
end

activityspark/app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  # GET /pledges
  # GET /pledges.json
  def index
    @pledges = Pledge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @pledges }
    end
  end

  # GET /pledges/1
  # GET /pledges/1.json
  def show
    @pledge = Pledge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @pledge }
    end
  end

  # GET /pledges/new
  # GET /pledges/new.json
  def new
    @pledge = Pledge.new

    if params[:event_id]
      event = Event.find(params[:event_id])
      @pledge.title = event.title
      @pledge.location = event.location
    end

    respond_to do |format|
      format.html # new.html.erb
    end
  end
  
  def update
	@pledge = Pledge.find(params[:pledge_id])
	redirect_to :action => 'show', :id => @pledge.id
  end
  
  # GET /pledges/1/edit
  # def edit
    # @pledge = Pledge.find(params[:id])
  # end

  # POST /pledges
  # POST /pledges.json
  def create
    @pledge = Pledge.new(params[:pledge])
    
    @pledge.curr_num_pledged = 1;
    @pledge.status = "unpurchased"
      if @pledge.save
        redirect_to :action => 'add_payment', :id => @pledge.id
      else
        format.html { render :action => "successful_pledge" }
      end
  end
  
  def add_payment
    @pledge = Pledge.find(params[:id])
  end
  
  def save_payment
    @pledge = Pledge.find(params[:pledge_id])
	
	@participant = Participant.new(params[:participant])
	@participant.save
	
    @pledge.participants << @participant
	@pledge.host_id = @participant.id
	
    respond_to do |format|
      if @pledge.save
        format.html { redirect_to :action=> "add_friends", :id=>@pledge.id}
     # else
    #    format.html { render :action => "new" }
      end
    end
  end
  
  def add_friends
      @pledge = Pledge.find(params[:id])
	  @host = Participant.find(@pledge.host_id)
  end
  
  def save_friends
    @pledge = Pledge.find(params[:id])
	@host = Participant.find(@pledge.host_id)

    #split emails
    params[:all_emails].split(/\s/).each() {|s|
      s = s.strip
      if s && s.length > 0
        participant = Participant.new()
        participant.email_addr = s
        @pledge.participants << participant
      end
    }
    
    #Now send the invite emails
    send_invites(@pledge, params[:message])
    
    respond_to do |format|
      if @pledge.save
        format.html { redirect_to :action=> "successful_pledge", :id=>@pledge.id}
      else
        format.html { render :action => "successful_pledge" }
      end
    end
  end

  def successful_pledge
    @pledge = Pledge.find(params[:id])
  end

  def accept_invite
    @pledge = Pledge.find(params[:id])
    @participant = Participant.find(params[:user])
  end
  
  def save_accept_invite
    @pledge = Pledge.find(params[:id])
    @pledge.curr_num_pledged = @pledge.curr_num_pledged + 1
    @pledge.save
    if @pledge.curr_num_pledged >= @pledge.num_people_required
      send_matched(@pledge)
    end
  end
  

  # DELETE /pledges/1
  # DELETE /pledges/1.json
  def destroy
    @pledge = Pledge.find(params[:id])
    @pledge.destroy

    respond_to do |format|
      format.html { redirect_to pledges_url }
      format.json { head :ok }
    end
  end
end

activityspark/app/helpers/pledges_helper.rb
module PledgesHelper

end

activityspark/app/views/pledges/_form.html.erb
<%= stylesheet_link_tag "jquery.ui.all" %>
<%= stylesheet_link_tag "site" %>
<%= stylesheet_link_tag "jquery.ui.core" %>
<%= stylesheet_link_tag "jquery.ui.datepicker" %>
<%= javascript_include_tag "jquery.ui.core.min" %>
<%= javascript_include_tag "jquery.ui.datepicker.min" %>

<style type="text/css">
#text1
{
width: 180px;
}
#text2
{
width: 338px;
}
#text3
{
width: 120px;
}
#text6
{
width: 202px;
}
#TextArea1
{
width: 380px;
height: 58px;
}
.style1
{
    margin-left: 40px;
}
#Submit1
{
width: 102px;
}
#text4
{
width: 70px;
}
#text5
{
width: 71px;
}
</style>

<script type="text/javascript">
$(document).ready(function () {
        $("#instanceExpirationDate").datepicker();
        });
</script>

<%= form_for(@pledge) do |f| %>
  <% if @pledge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pledge.errors.count, "error") %> prohibited this pledge from being saved:</h2>

      <ul>
      <% @pledge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :host_id %><br />
    <%= f.number_field :host_id %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br />
    <%= f.text_field :total_price %>
  </div>
  <div class="field">
    <%= f.label :price_per_person %><br />
    <%= f.text_field :price_per_person %>
  </div>
  <div class="field">
    <%= f.label :num_people_required %><br />
    <%= f.number_field :num_people_required %>
  </div>
  <div class="field">
    <%= f.label :max_num_people %><br />
    <%= f.number_field :max_num_people %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.date_select :time %>
  </div>
  <div class="field">
    <%= f.label :deal_deadline %><br />
    <%= f.date_select :deal_deadline %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :curr_num_pledged %><br />
    <%= f.number_field :curr_num_pledged %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit 'Continue' %>
  </div>
<% end %>

activityspark/app/views/pledges/accept_invite.html.erb
<h2>Hi! <%= @participant.email_addr %></h2>

Activity Title <%= @pledge.title %> <br />
Activity Location <%= @pledge.location %> <br/>
Your Cost <%= @pledge.price_per_person %> <br />
Date <%= @pledge.time %> <br />
Deadline <%= @pledge.deal_deadline %> <br />
# People Pledged <%= @pledge.curr_num_pledged %> <br />
# People Required to Tip Deal <%= @pledge.num_people_required %> <br />
<div style="text-align:center; font-size: 2em;">
<%= form_for @participant, :url=>{:action=>:save_accept_invite, :id=>@pledge.id} do |f| %>
  <div class="actions">
    <%= f.submit 'Continue' %>
  </div>
<% end %>
</div>

activityspark/app/views/pledges/add_friends.html.erb
<script>
    $("#friendCustomMessage").live("keyup",function () {
        $("#customMsgTxt").html($("#friendCustomMessage").val());
    });

    function showCustomMessageField() {
        $("#showCustomMessageOption").hide();
        $("#customMessageTextBox").show();
    }

    var friendEmailAddressBoxRows = 2
    $(document).ready(function () {
       ;
        $("#friendEmailAddreses").live("keyup", function (e) {
            var keycode;
            if (window.event) keycode = window.event.keyCode;
            else if (e) keycode = e.which;
            else return true;
            if (keycode == 13) {
                friendEmailAddressBoxRows += 1;
                $("#friendEmailAddreses").attr("rows", friendEmailAddressBoxRows);
            }
        });

    });
    function updateMessage() {
    	var html = $("#emailPreviewBox").html();
    	$("#message_field")[0].value = html;
    	return true;
    }
</script>
<div id="pageBodyContainer">
        <div style="text-align:center;">
	<%= form_tag :action=>:save_friends, :id=>@pledge.id do %>
			<input type="hidden" id="message_field" name="message" value=""/>
            <div id="inviteFriendFormContents">
                <div id="inviteYourFriendsHeader">
                    <h2 class="form">Invite Your Friends</h2>
                </div>
                <div>
                    <div id="emailAddressHeader">Email Addresses: (one email per line)</div>
                    <div><textarea id="friendEmailAddreses" name="all_emails" cols="50" rows="2" style="width: 100%; height: 150px;"></textarea></div>
                </div>
                <div>
                <br />
                    <h2 class="form">Invite Message:</h2>
                    <div id="emailPreviewBox">
                        <p><%= @host.first_name %> (<%= @host.email_addr %>) has invited you to join this event.</p>
                        <p>
                            <b>Event Details:</b><br /><br />
                            Title: <%= @pledge.title %><br />
                            Location: <%= @pledge.location %><br />
                            Date/Time: <%= @pledge.time %><br />
                        </p>
                        <p>
                            <b><%= @host.first_name %>'s Message:</b>
                            <div id="customMsgTxt"></div>
                        </p>
                        <p>
                            <a href="http://www.activityspark.com/pledges/accept_invite/<%= params[:id] %>">Click here</a> to see more details and to join <%= @host.first_name %> at this event!
                        </p>
                        <p>
                            Count me in!
                        </p>
                    </div>
                </div>
                <div onclick="showCustomMessageField()" id="showCustomMessageOption">Add Custom Message</div>
                <div id="customMessageTextBox">
                    <br />
                    <div id="customMessageHeading">Custom Message:</div>
                    <div><textarea id="friendCustomMessage" cols="50" rows="6"></textarea></div>
                </div>
                <div style="text-align:right;margin-top:20px;">
                    <div><input type="submit" value="Checkout" id="sendFriendInvites" onclick="updateMessage()"/></div>
                </div>
            </div>
	<% end %>
        </div>
</div>

activityspark/app/views/pledges/add_payment.html.erb
<div id="pageBodyContainer">
<%= form_for :participant, :url => { :action => :save_payment, :pledge_id => @pledge.id} do |f| %>

<div class="form">
  <h1>Add Payment Info</h1>

  <div class="field">
    <%= f.label 'First Name' %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label 'Last Name' %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label 'Email Address' %>
    <%= f.text_field :email_addr %>
  </div>
  <div class="field">
    <%= f.label 'Street Address' %>
    <%= f.text_field :street_addr %>
  </div>
  <div class="field">
    <%= f.label 'City' %>
    <%= f.number_field :city %>
  </div>
  <div class="field">
    <%= f.label 'State' %>
    <%= f.number_field :state %>
  </div>
  <div class="field">
    <%= f.label 'Zip Code' %>
    <%= f.text_field :zip %>
  </div>
  <h2>Credit Card Information</h2>
  <div class="field">
    <%= f.label 'Card Number' %>
    <%= f.text_field :cc %>
  </div>  
  <div class="field">
    <%= f.label 'Expiration Date (MM/YY)' %>
    <%= f.text_field :expiration_dt %>
  </div>
  <h2>Contact Information</h2>
  <div class="field">
    <%= f.label 'Phone' %>
    <%= f.text_field :phone %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Continue' %>
  </div>
  
</div>
<% end %>
</div>

activityspark/app/views/pledges/checkout.html.erb
        <div style="text-align:center"><h2>Checkout Form</h2></div>
        <div style="text-align:center;margin:0 auto;width:453px;">
	   <%= form_for(@pledge) do |f| %>
            <table style="width: 100%;text-align:left;">
	            <tr>
		            <td style="width: 255px">First Name</td>
		            <td>Last Name</td>
	            </tr>
	            <tr>
		            <td style="width: 255px">
			<%= f.text
		            <td>
		            <input id="text2" type="text" style="width: 205px" /></td>
	            </tr>
	            <tr>
		            <td style="width: 255px">&nbsp;</td>
		            <td>&nbsp;</td>
	            </tr>
	            <tr>
		            <td style="width: 255px; height: 23px;">Company Name (optional)</td>
		            <td style="height: 23px"></td>
	            </tr>
	            <tr>
		            <td colspan="2">
		            <input id="text3" type="text" style="width: 500px" /></td>
	            </tr>
	            <tr>
		            <td style="width: 255px">&nbsp;</td>
		            <td>&nbsp;</td>
	            </tr>
	            <tr>
		            <td style="width: 255px">Street Address</td>
		            <td>&nbsp;</td>
	            </tr>
	            <tr>
		            <td style="height: 26px;" colspan="2">
		            <input id="text4" type="text" style="width: 500px" /></td>
	            </tr>
	            <tr>
		            <td style="width: 255px">&nbsp;</td>
		            <td>&nbsp;</td>
	            </tr>
	            <tr>
		            <td style="width: 255px">City or Town</td>
		            <td>State/Prov</td>
	            </tr>
	            <tr>
		            <td style="width: 255px; height: 29px;">
		            <input id="text5" type="text" style="width: 205px" /></td>
		            <td style="height: 29px">
		            <input id="text6" type="text" style="width: 64px" /></td>
	            </tr>
	            <tr>
		            <td style="width: 255px">&nbsp;</td>
		            <td>&nbsp;</td>
	            </tr>
	            <tr>
		            <td style="width: 255px">Postal Code</td>
		            <td>Country</td>
	            </tr>
	            <tr>
		            <td style="width: 255px; height: 45px;">
		            <input id="text7" type="text" style="width: 205px" /></td>
		            <td style="height: 45px">
		            
			            <select name="Select1" style="width: 120px">
			            <option></option>
			            <option selected="selected">Unite States</option>
			            <option>Argentina</option>
			            <option>Australia</option>
			            <option>Belgium</option>
			            <option>Brazil</option>
			            <option>Canada</option>
			            <option>Chaina</option>
			            <option>Chile</option>
			            <option>Colombia</option>
			            <option>Costa Rica</option>
			            <option>Mexico</option>
			            </select>
		            </td>
	            </tr>
	            <tr>
		            <td style="width: 255px; height: 26px;">
		            <strong>Credit Card Information</strong></td>
		            <td style="height: 26px">
		            </td>
	            </tr>
	            <tr>
		            <td style="width: 255px; height: 23px;" colspan="2"><img src="cards.png" alt="accepted cards"/></td>
	            </tr>
	            <tr style="display:none;">
		            <td style="width: 255px; height: 23px;" colspan="2">
			            Name on the Card
                        <br /><input id="text11" type="text" style="width: 205px" />
                    </td>
	            </tr>
	            <tr>
		            <td style="width: 255px; height: 26px;" colspan=2">
		            Card Number
                    <br />
                    <input id="text12" type="text" style="width: 239px" />
		            </td>
	            </tr>
	            <tr>
		            <td style="width: 255px; height: 26px;" colspan="2">Expiration date<br />
			            <select name="Select2" style="width: 51px">
			            <option></option>
			            <option>Jan</option>
			            <option>Feb</option>
			            <option>Mar</option>
			            <option>Apr</option>
			            <option>May</option>
			            <option>Jun</option>
			            <option>Jul</option>
			            <option>Aug</option>
			            <option>Sep</option>
			            <option>Oct</option>
			            <option>Nov</option>
			            <option>Dec</option>
			            </select>&nbsp;&nbsp;
		            <input id="text13" type="text" style="width: 59px" />
		            </td>
	            </tr>
                <tr>
		            <td style="width: 255px; height: 26px;">
                    <br /><br />
		            <strong>Contact Information</strong></td>
		            <td style="height: 26px">
		            </td>
	            </tr>
	            <tr>
		            <td style="width: 255px; height: 23px;">Email Address</td>
		            <td style="height: 26px"></td>
	            </tr>
	            <tr>
		            <td style="height: 26px;" colspan="2">
		            <input id="text8" type="text" style="width: 409px" /></td>
	            </tr>
	            <tr>
		            <td style="height: 26px;">Daytime phone</td>
		            <td style="height: 26px;">Evening Phone</td>
	            </tr>
	            <tr>
		            <td style="height: 25px;">
		            <input id="text9" type="text" style="width: 224px" /></td>
		            <td style="height: 25px;">
		            <input id="text10" type="text" style="width: 221px" /></td>
	            </tr>
                <tr>
                    <td colspan="2" style="height:26px;" align="center">
	                    <input name="Submit1" style="width: 179px" type="submit" value="Checkout" />
                    </td>
                </tr>
            </table>
	   <% end %>
            </div>

activityspark/app/views/pledges/edit.html.erb
<h1>Editing pledge</h1>

<%= render 'form' %>

<%= link_to 'Show', @pledge %> |
<%= link_to 'Back', pledges_path %>

activityspark/app/views/pledges/index.html.erb
<h1>Listing pledges</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Host</th>
    <th>Total price</th>
    <th>Price per person</th>
    <th>Num people required</th>
    <th>Max num people</th>
    <th>Time</th>
    <th>Deal deadline</th>
    <th>Notes</th>
    <th>Curr num pledged</th>
    <th>Status</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pledges.each do |pledge| %>
  <tr>
    <td><%= pledge.title %></td>
    <td><%= pledge.host_id %></td>
    <td><%= pledge.total_price %></td>
    <td><%= pledge.price_per_person %></td>
    <td><%= pledge.num_people_required %></td>
    <td><%= pledge.max_num_people %></td>
    <td><%= pledge.time %></td>
    <td><%= pledge.deal_deadline %></td>
    <td><%= pledge.notes %></td>
    <td><%= pledge.curr_num_pledged %></td>
    <td><%= pledge.status %></td>
    <td><%= pledge.location %></td>
    <td><%= link_to 'Show', pledge %></td>
    <td><%= link_to 'Edit', edit_pledge_path(pledge) %></td>
    <td><%= link_to 'Destroy', pledge, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pledge', new_pledge_path %>

activityspark/app/views/pledges/new.html.erb
    <%= stylesheet_link_tag "site" %>
    <%= stylesheet_link_tag "jquery.ui.core" %>
    <%= stylesheet_link_tag "jquery.ui.datepicker" %>
    <%= javascript_include_tag "jquery.ui.core.min" %>
    <%= javascript_include_tag "jquery.ui.datepicker.min" %>

    <style type="text/css">
        #text1
        {
            width: 180px;
        }
        #text2
        {
            width: 338px;
        }
        #text3
        {
            width: 120px;
        }
        #text6
        {
            width: 202px;
        }
        #TextArea1
        {
            width: 380px;
            height: 58px;
        }
        .style1
        {
            margin-left: 40px;
        }
        #Submit1
        {
            width: 102px;
        }
        #text4
        {
            width: 70px;
        }
        #text5
        {
            width: 71px;
        }
        .form_table td{
            padding-top: 3px;
        }
    </style>
<div id="pageBodyContainer">
<%= form_for :pledge, :url=>{:action => :create, :id => @pledge} do |f| %>
  <% if @pledge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pledge.errors.count, "error") %> prohibited this pledge from being saved:</h2>

      <ul>
      <% @pledge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div style="text-align:center;padding-top:20px;padding-bottom:20px;font-weight:bold;font-size:20px;">
<h1>Spark an Activity!</h1>
</div>
<div style="text-align:left;margin-left:50px;">
	<table style="width: 100%" class="form_table">

	<tr>
	    <td style="width: 241px;height: 26px;"><%= f.label :title %></td>
	    <td><%= f.text_field :title, :disabled => "disabled"%></td>
	</tr>
  <tr>
    <td><%= f.label 'Time of event' %></td>
    <td><%= f.text_field :time, :id => "select_time" %></td>
  </tr>
  <tr>
	  <td class="field"><%= f.label 'Location of event' %></td>
	  <td><%= f.text_field :location, :disabled => "disabled" %></td>
  </tr>
  <tr>
  	<td class="field"><%= f.label '# of people required' %></td>
	<td><%= f.number_field :num_people_required %></td>
  </tr>
  <tr>
	  <td class="field"><%= f.label 'Max Friends' %></td>
	  <td><%= f.number_field :max_num_people %></td>
  </tr>
  <tr>
	  <td class="field"><%= f.label 'Estimated Cost' %></td>
	  <td><%= f.text_field :total_price %></td>
  </tr>
  <tr>
	  <td class="field"><%= f.label 'Expiration Date' %></td>
	  <td><%= f.text_field :deal_deadline, :id => "select_time" %></td>
  </tr>
	<tr> 
  		<td class="actions" colspan="2">
        <br/>
    	<%= f.submit 'Spark It!' %>
  		</td>
    </tr>
  </table>
</div>
<% end %>
</div>

activityspark/app/views/pledges/save_accept_invite.html.erb
<% if @pledge.curr_num_pledged.to_i >= @pledge.num_people_required.to_i %>
	<h2>The Activity Is On!</h2>
<% else %>
	<h2>Invite Your Friends!</h2>
<% end %>


# People Pledged: <%= @pledge.curr_num_pledged %> <br />
# People Remaining to Tip Activity: <%= @pledge.num_people_required.to_i - @pledge.curr_num_pledged.to_i %> <br />

Activity Title: <%= @pledge.title %> <br />
Activity Location: <%= @pledge.location %> <br/>

activityspark/app/views/pledges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @pledge.title %>
</p>

<p>
  <b>Host:</b>
  <%= @pledge.host_id %>
</p>

<p>
  <b>Total price:</b>
  <%= @pledge.total_price %>
</p>

<p>
  <b>Price per person:</b>
  <%= @pledge.price_per_person %>
</p>

<p>
  <b>Num people required:</b>
  <%= @pledge.num_people_required %>
</p>

<p>
  <b>Max num people:</b>
  <%= @pledge.max_num_people %>
</p>

<p>
  <b>Time:</b>
  <%= @pledge.time %>
</p>

<p>
  <b>Deal deadline:</b>
  <%= @pledge.deal_deadline %>
</p>

<p>
  <b>Notes:</b>
  <%= @pledge.notes %>
</p>

<p>
  <b>Curr num pledged:</b>
  <%= @pledge.curr_num_pledged %>
</p>

<p>
  <b>Status:</b>
  <%= @pledge.status %>
</p>

<p>
  <b>Location:</b>
  <%= @pledge.location %>
</p>


<%= link_to 'Edit', edit_pledge_path(@pledge) %> |
<%= link_to 'Back', pledges_path %>

activityspark/app/views/pledges/successful_pledge.html.erb
<div id="pageBodyContainer">

Event Title <%= @pledge.title %> <br />
Event Location <%= @pledge.location %> <br/>
Total Price <%= @pledge.total_price %> <br />
Price/Person <%= @pledge.price_per_person %> <br />
# People Required <%= @pledge.num_people_required %> <br />
Max # People <%= @pledge.max_num_people %> <br />
Date <%= @pledge.time %> <br />
Deadline <%= @pledge.deal_deadline %> <br />
# People Pledged <%= @pledge.curr_num_pledged %> <br />
<br>
My Info:<br/>
First Name <%= @pledge.get_host.first_name %> <br />
Last Name <%= @pledge.get_host.last_name %> <br />
Email <%= @pledge.get_host.email_addr %> <br />
Street <%= @pledge.get_host.street_addr %> <br />
City <%= @pledge.get_host.city %> <br />
State <%= @pledge.get_host.state %> <br />
Zip <%= @pledge.get_host.zip %> <br />
Phone <%= @pledge.get_host.phone %> <br />
<br/>
My Friends<br/>
<% @pledge.participants.each {|p| %>
	Email: <%= p.email_addr %><br/>
<% } %>
<br />

</div>

activityspark/app/views/pledges/update.html.erb
This is a test.